name: unit tests

on:
  push:
    branches: 
      - master

jobs:
  perform-unit-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Perform unit tests
      - name: Perform unit tests
        run: dotnet test CssClassInlineBuilder.Test -l "console;verbosity=normal" -v:q --nologo